version: '3'

services:
  todo-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - todo-db
    environment:
      MYSQL_HOST: todo-db
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: todo_database

  todo-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: todo_database
